[package]
name = "aoc2019"
version = "0.1.0"
authors = ["gisle"]
edition = "2018"
default-run = "day01"

[lib]
name = "common"
path = "src/lib.rs"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[dependencies]
